{% set name = "sparse_dot_topn" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 721f2bc4615c6050084f96518322f1dcb2b82a1016a4d9a1fe508d351d992136

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - numpy >=1.16.6
    - cython
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - setuptools

test:
  imports:
    - sparse_dot_topn

about:
  home: https://github.com/ing-bank/sparse_dot_topn
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Sparse_dot_topn provides a fast way to performing a sparse matrix multiplication
    followed by top-n multiplication result selections.
  description: |
    Comparing very large feature vectors and
    picking the best matches, in practice often results in performing sparse matrix multiplication
    followed by selecting the top-n multiplication results. In this package, we implement a
    customized Cython function for this purpose. When comparing our Cythonic approach to doing the
    same use with SciPy and NumPy functions, our approach improves the speed by about 40% and
    reduces memory consumption.
  doc_url: https://pypi.org/project/sparse-dot-topn/
  dev_url: https://github.com/ing-bank/sparse_dot_topn

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
